theme: jekyll-theme-cayman
title: Joseph McPhearson
author: Joseph McPhearson
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website. Here you can find information about my projects, blog posts, and more.
baseurl: "/about" # the subpath of your site, e.g. /blog
url: "https://josephmc-swosu.github.io" # the base hostname & protocol for your site
sass:
  style: compressed
  sass_dir: _sass
  css_dir: assets/css