title: Joseph McPhearson
email: josephmcphearson@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website. Here you can find information about my projects, blog posts, and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://JosephMc-SWOSU.github.io" # the base hostname & protocol for your site

# Minimal Mistakes theme settings
remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Site author
author:
  name: "Joseph McPhearson"
  avatar: "/assets/images/avatar.png"
  bio: "Computer Science Student, Tech Enthusiast, and Miata driver."
  location: "Weatherford, OK"
  email: "josephmcphearson@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/josephmc-swosu"

# Social sharing settings
social:
  github: josephmc-swosu

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-titles-from-headings
  - jekyll-mentions
  - jekyll-remote-theme
